### PR TITLE
Nbo/make email and roles non case sensitive for rbac prod 11274

### PR DESCRIPTION
**Pull request by nborde-CSM**
Before creating a PR, please check that:
- [ ] Code is clean
- [ ] Tests are still working (cypress tests and `yarn test`)
- [ ] Changes don't cause new errors or warnings in browser console
- [ ] Documentation is up-to-date
- [ ] Breaking changes are clearly identified with [conventional commits](https://kapeli.com/cheat_sheets/Conventional_Commits.docset/Contents/Resources/Documents/index)

### CODE REVIEW

**Review by esasova — APPROVED** [review]
LGTM :+1:

**Review by csm-thu — COMMENTED** [review]
@nborde-CSM could you modify the [existing unit tests](https://github.com/Cosmo-Tech/azure-sample-webapp/blob/main/src/utils/__test__/SecurityUtils.spec.js) to check that user ids in ACL are no longer case-sensitive?

**Review by csm-thu — APPROVED** [review]
LGTM :+1:

**Review by esasova — APPROVED** [review]
LGTM :+1:

**Pull request merged**
