### PR TITLE
VMI/number validator prod 7582

### PR DESCRIPTION
**Pull request by COSMO-VMI**

### CODE REVIEW

**Review by csm-thu — COMMENTED** [review]
Hello ! The dependency _react-number-format_ doesn't seem to be used. Can we remove it ?

**Review by Nikeleos — APPROVED** [review]

**Comment by COSMO-VMI** [comment]
> Hello ! The dependency _react-number-format_ doesn't seem to be used. Can we remove it ?

Oh, I added the dependency here for the number input component, but I should add it in the ui repo, which contains the component, right?

**Comment by csm-thu** [comment]
> Oh, I added the dependency here for the number input component, but I should add it in the ui repo, which contains the component, right?

That's correct, this dependency is only used in the component located in the UI repository, and since it is a direct dependency (i.e. not a peer dependency) it does not need to be added in the webapp repository :)

**Review by csm-thu — APPROVED** [review]
LGTM :+1:

**Pull request merged**
