### PR TITLE
test: add optional non-capturing groups to support all versions in API URL

### PR DESCRIPTION
**Pull request by csm-thu**

### CODE REVIEW

**Review by esasova — APPROVED** [review]
LGTM :+1:

**Review by Guismus — APPROVED** [review]
LGTM :+1:

**Review by ardvi — APPROVED** [review]
LGTM :+1:

**Comment by csm-thu** [comment]
Merged manually into _main_ branch (commit dd417b7f96b29d2a46c35521c0ae237598d81c10)

**Pull request closed without merging**
